### ISSUE TITLE
How to run profileAllTestFiles? Not included in mvn test?

### ISSUE THREAD

**Issue by proycon** [weblicht/profiler#2]
Perhaps I'm missing something obvious (I'm not much of a java guy), but the ``profileAllTestFiles`` test doesn't seem to be included when running mvn test, how should these tests be run?

**Comment by emanueldima** [comment]
This test should run, but maybe you're mislead by the previous code. The current implementation has a basic check of the root xml tag, and can recognize folia based on that. You may want to change it: https://github.com/weblicht/profiler/blob/651e4a085eb4f1d30a4bd2d463c9e858016bd21d/src/main/java/eu/clarin/switchboard/profiler/xml/XmlProfiler.java#L27
and used here: https://github.com/weblicht/profiler/blob/651e4a085eb4f1d30a4bd2d463c9e858016bd21d/src/main/java/eu/clarin/switchboard/profiler/xml/XmlProfiler.java#L71

**Comment by proycon** [comment]
Thanks, I hadn't seen that part yet indeed and have adapted it now. But I guess I'm still confused how the tests in this ``ProfileAllTestFiles`` are supposed to run, you're not saying that part is old obsolete code, are you?

https://github.com/weblicht/profiler/blob/651e4a085eb4f1d30a4bd2d463c9e858016bd21d/src/test/java/eu/clarin/switchboard/profiler/ProfileAllTestFiles.java#L21

``mvn test`` only gives me:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running eu.clarin.switchboard.profiler.DefaultProfilerTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Apr 30, 2020 12:55:35 PM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: J2KImageReader not loaded. JPEG2000 files will not be processed.
See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
for optional dependencies.

Apr 30, 2020 12:55:35 PM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: Tesseract OCR is installed and will be automatically applied to image files unless
you've excluded the TesseractOCRParser from the default parser.
Tesseract may dramatically slow down content extraction (TIKA-2359).
As of Tika 1.15 (and prior versions), Tesseract is automatically called.
In future versions of Tika, users may need to turn the TesseractOCRParser on via TikaConfig.
Apr 30, 2020 12:55:35 PM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: org.xerial's sqlite-jdbc is not loaded.
Please provide the jar on your classpath to parse sqlite files.
See tika-parsers/pom.xml for the correct version.
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.994 sec
Running eu.clarin.switchboard.profiler.OptimaizeLanguageDetectorTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.898 sec
Running eu.clarin.switchboard.profiler.api.ProfileTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running eu.clarin.switchboard.profiler.TextExtractorTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.263 sec
Running eu.clarin.switchboard.profiler.DefaultMatcherTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec
```

(I guess it only runs ``*Test.class`` and ``ProfileAllTestFiles.class`` doesn't match)?

**Comment by emanueldima** [comment]
Oh, you're absolutely right. I develop in IDEA (Community Edition) and all the tests run there without a problem, but maven only runs the ones with the Test suffix. Please rename the file to something like `ProfileAllFilesTest`, this will fix it.

**Comment by proycon** [comment]
ok thanks! makes sense! will do!
